import type { SystemDoc } from './content';

// AUTHORED CONTENT — generated by the learn-content pass (per-system explainers, KaTeX equations,
// core code, reference links), authored against the archetype source. Regenerate, don't hand-edit.
export const SYSTEM_DOCS: Record<string, SystemDoc> = {
  "lorenz": {
    "title": "Lorenz",
    "about": "The original strange attractor, born from a simplified model of atmospheric convection. A strange attractor is a shape that a chaotic system endlessly traces but never exactly repeats, so nearby starting points drift apart fast yet all settle onto the same butterfly-shaped surface. It launched the popular idea of the 'butterfly effect.'",
    "howItWorks": "Three coupled rates push each point around two spiraling lobes, and the nonlinear cross-terms keep flipping it unpredictably between them.",
    "equations": [
      {
        "label": "",
        "latex": "\\begin{aligned}\\dot{x}&=\\sigma\\,(y-x)\\\\\\dot{y}&=x\\,(\\rho-z)-y\\\\\\dot{z}&=xy-\\beta z\\end{aligned}"
      }
    ],
    "params": [
      {
        "key": "sigma",
        "symbol": "\\sigma",
        "meaning": "how strongly x and y pull toward each other (Prandtl number)"
      },
      {
        "key": "rho",
        "symbol": "\\rho",
        "meaning": "the driving force; higher values push the system into chaos (Rayleigh number)"
      },
      {
        "key": "beta",
        "symbol": "\\beta",
        "meaning": "geometric damping that shrinks the z motion"
      }
    ],
    "code": "o[0] = p.sigma * (x[1] - x[0]);\no[1] = x[0] * (p.rho - x[2]) - x[1];\no[2] = x[0] * x[1] - p.beta * x[2];",
    "links": [
      {
        "label": "Lorenz system (Wikipedia)",
        "url": "https://en.wikipedia.org/wiki/Lorenz_system"
      },
      {
        "label": "Lorenz 1963, Deterministic Nonperiodic Flow",
        "url": "https://journals.ametsoc.org/view/journals/atsc/20/2/1520-0469_1963_020_0130_dnf_2_0_co_2.xml"
      }
    ]
  },
  "rossler": {
    "title": "Rössler",
    "about": "A deliberately minimal chaotic system, designed to be as simple as possible while still being strange. A strange attractor is a never-repeating path that nonetheless stays trapped on one fractal shape. It produces a single spiraling sheet with one outward fold, like a rolled-up ribbon.",
    "howItWorks": "Points slowly spiral outward in a plane, and a single nonlinear term yanks them back up and over whenever they wander too far, folding the flow into chaos.",
    "equations": [
      {
        "label": "",
        "latex": "\\begin{aligned}\\dot{x}&=-(y+z)\\\\\\dot{y}&=x+a\\,y\\\\\\dot{z}&=b+z\\,(x-c)\\end{aligned}"
      }
    ],
    "params": [
      {
        "key": "a",
        "symbol": "a",
        "meaning": "sets how fast the spiral expands outward"
      },
      {
        "key": "b",
        "symbol": "b",
        "meaning": "a constant kick that keeps z from dying out"
      },
      {
        "key": "c",
        "symbol": "c",
        "meaning": "threshold where the fold kicks in; tuning it switches chaos on and off"
      }
    ],
    "code": "o[0] = -(x[1] + x[2]);\no[1] = x[0] + p.a * x[1];\no[2] = p.b + x[2] * (x[0] - p.c);",
    "links": [
      {
        "label": "Rössler attractor (Wikipedia)",
        "url": "https://en.wikipedia.org/wiki/R%C3%B6ssler_attractor"
      },
      {
        "label": "Rössler 1976, An Equation for Continuous Chaos",
        "url": "https://www.sciencedirect.com/science/article/abs/pii/0375960176901018"
      }
    ]
  },
  "aizawa": {
    "title": "Aizawa",
    "about": "A richly ornamented attractor that wraps into a sphere-like shell with a spike poking through its top. A strange attractor is a non-repeating trajectory confined to a single intricate shape. Its decorative, almost organic form makes it a favorite for visualizations.",
    "howItWorks": "A rotation term spins points around an axis while higher-order terms in z carve out the central hole and grow the protruding spike.",
    "equations": [
      {
        "label": "",
        "latex": "\\begin{aligned}\\dot{x}&=(z-b)\\,x-d\\,y\\\\\\dot{y}&=d\\,x+(z-b)\\,y\\\\\\dot{z}&=c+a\\,z-\\tfrac{z^{3}}{3}-(x^{2}+y^{2})(1+e\\,z)+f\\,z\\,x^{3}\\end{aligned}"
      }
    ],
    "params": [
      {
        "key": "a",
        "symbol": "a",
        "meaning": "linear growth/decay along the z axis"
      },
      {
        "key": "b",
        "symbol": "b",
        "meaning": "shifts the rotation plane up or down"
      },
      {
        "key": "c",
        "symbol": "c",
        "meaning": "constant drive feeding the z motion"
      },
      {
        "key": "d",
        "symbol": "d",
        "meaning": "rotation speed around the vertical axis"
      },
      {
        "key": "e",
        "symbol": "e",
        "meaning": "couples height into the inward pull, shaping the shell"
      },
      {
        "key": "f",
        "symbol": "f",
        "meaning": "strength of the asymmetric term that forms the spike"
      }
    ],
    "code": "o[0] = (zz - p.b) * xx - p.d * yy;\no[1] = p.d * xx + (zz - p.b) * yy;\no[2] = p.c + p.a*zz - zz^3/3 - (xx^2+yy^2)*(1+p.e*zz) + p.f*zz*xx^3;",
    "links": [
      {
        "label": "Aizawa attractor (algosome reference)",
        "url": "http://www.algosome.com/articles/aizawa-attractor-chaos.html"
      }
    ]
  },
  "thomas": {
    "title": "Thomas",
    "about": "A beautifully symmetric attractor where all three coordinates obey the same rule, cycled around. A strange attractor is a wandering path that never repeats yet stays on one shape. Here the result looks like a meandering, labyrinthine tangle with threefold symmetry.",
    "howItWorks": "Each coordinate is driven by the sine of the next one minus a little friction, so the points coast through a sinusoidal maze that gently dissipates.",
    "equations": [
      {
        "label": "",
        "latex": "\\begin{aligned}\\dot{x}&=\\sin(y)-b\\,x\\\\\\dot{y}&=\\sin(z)-b\\,y\\\\\\dot{z}&=\\sin(x)-b\\,z\\end{aligned}"
      }
    ],
    "params": [
      {
        "key": "b",
        "symbol": "b",
        "meaning": "friction; small values give sprawling chaos, large values calm it to a loop"
      }
    ],
    "code": "o[0] = Math.sin(x[1]) - p.b * x[0];\no[1] = Math.sin(x[2]) - p.b * x[1];\no[2] = Math.sin(x[0]) - p.b * x[2];",
    "links": [
      {
        "label": "Thomas' cyclically symmetric attractor (Wikipedia)",
        "url": "https://en.wikipedia.org/wiki/Thomas%27_cyclically_symmetric_attractor"
      }
    ]
  },
  "halvorsen": {
    "title": "Halvorsen",
    "about": "A cyclically symmetric attractor that curls into three interlocking arms. A strange attractor is a trajectory that never retraces itself but stays bound to a single shape. Halvorsen's version has a graceful, scroll-like symmetry shared across all three axes.",
    "howItWorks": "Each coordinate decays while being pushed by the other two plus a squared feedback term, and that symmetric coupling folds the flow into spiraling lobes.",
    "equations": [
      {
        "label": "",
        "latex": "\\begin{aligned}\\dot{x}&=-a\\,x-4y-4z-y^{2}\\\\\\dot{y}&=-a\\,y-4z-4x-z^{2}\\\\\\dot{z}&=-a\\,z-4x-4y-x^{2}\\end{aligned}"
      }
    ],
    "params": [
      {
        "key": "a",
        "symbol": "a",
        "meaning": "damping strength shared by all three axes; controls how tightly the arms wind"
      }
    ],
    "code": "o[0] = -p.a*x[0] - 4*x[1] - 4*x[2] - x[1]*x[1];\no[1] = -p.a*x[1] - 4*x[2] - 4*x[0] - x[2]*x[2];\no[2] = -p.a*x[2] - 4*x[0] - 4*x[1] - x[0]*x[0];",
    "links": [
      {
        "label": "Halvorsen attractor (3D-Meier reference)",
        "url": "http://www.3d-meier.de/tut19/Seite3.html"
      }
    ]
  },
  "chen": {
    "title": "Chen",
    "about": "A close relative of the Lorenz system that produces a more tightly knotted double scroll. A strange attractor is a path that wanders forever without repeating while staying on one shape. Chen's attractor is a textbook example of chaos engineered to be harder to control than Lorenz.",
    "howItWorks": "It mixes Lorenz-style coupling with extra cross-terms so the two scrolls wind around each other more aggressively.",
    "equations": [
      {
        "label": "",
        "latex": "\\begin{aligned}\\dot{x}&=a\\,(y-x)\\\\\\dot{y}&=(c-a)\\,x-xz+c\\,y\\\\\\dot{z}&=xy-b\\,z\\end{aligned}"
      }
    ],
    "params": [
      {
        "key": "a",
        "symbol": "a",
        "meaning": "coupling strength between x and y"
      },
      {
        "key": "b",
        "symbol": "b",
        "meaning": "damping on the z direction"
      },
      {
        "key": "c",
        "symbol": "c",
        "meaning": "drive parameter that sets the chaotic regime"
      }
    ],
    "code": "o[0] = p.a * (x[1] - x[0]);\no[1] = (p.c - p.a) * x[0] - x[0] * x[2] + p.c * x[1];\no[2] = x[0] * x[1] - p.b * x[2];",
    "links": [
      {
        "label": "Multiscroll / Chen attractor (Wikipedia)",
        "url": "https://en.wikipedia.org/wiki/Multiscroll_attractor"
      },
      {
        "label": "Chen & Ueta 1999, Yet Another Chaotic Attractor",
        "url": "https://www.worldscientific.com/doi/10.1142/S0218127499001024"
      }
    ]
  },
  "dadras": {
    "title": "Dadras",
    "about": "A multi-wing attractor that fans out into several lobes at once. A strange attractor is a non-repeating trajectory locked onto a single fractal shape. Dadras's system was designed to generate these multi-winged forms from relatively few terms.",
    "howItWorks": "Cross-product terms between the coordinates create several outward-pointing wings, and the points hop chaotically among them.",
    "equations": [
      {
        "label": "",
        "latex": "\\begin{aligned}\\dot{x}&=y-p\\,x+o\\,yz\\\\\\dot{y}&=r\\,y-xz+z\\\\\\dot{z}&=c\\,xy-e\\,z\\end{aligned}"
      }
    ],
    "params": [
      {
        "key": "p",
        "symbol": "p",
        "meaning": "damping on x"
      },
      {
        "key": "o",
        "symbol": "o",
        "meaning": "strength of the y-z coupling feeding into x"
      },
      {
        "key": "r",
        "symbol": "r",
        "meaning": "growth rate of y"
      },
      {
        "key": "c",
        "symbol": "c",
        "meaning": "strength of the x-y product driving z"
      },
      {
        "key": "e",
        "symbol": "e",
        "meaning": "damping on z"
      }
    ],
    "code": "out[0] = x[1] - P.p*x[0] + P.o*x[1]*x[2];\nout[1] = P.r*x[1] - x[0]*x[2] + x[2];\nout[2] = P.c*x[0]*x[1] - P.e*x[2];",
    "links": [
      {
        "label": "Dadras et al. 2009, A novel three-dimensional autonomous chaotic system",
        "url": "https://www.sciencedirect.com/science/article/abs/pii/S0375960109009311"
      }
    ]
  },
  "lorenz84": {
    "title": "Lorenz-84",
    "about": "A low-order model of the large-scale atmospheric circulation, distinct from the famous 1963 system. A strange attractor is a never-repeating path confined to one shape. This one captures how the mid-latitude jet stream and weather waves jostle each other chaotically.",
    "howItWorks": "A westerly wind variable trades energy with two wave variables through quadratic coupling, while constant forcing terms keep the climate from settling down.",
    "equations": [
      {
        "label": "",
        "latex": "\\begin{aligned}\\dot{x}&=-y^{2}-z^{2}-a\\,x+a\\,F\\\\\\dot{y}&=xy-b\\,xz-y+G\\\\\\dot{z}&=b\\,xy+xz-z\\end{aligned}"
      }
    ],
    "params": [
      {
        "key": "a",
        "symbol": "a",
        "meaning": "damping rate of the mean westerly flow"
      },
      {
        "key": "b",
        "symbol": "b",
        "meaning": "strength of the wave-wave coupling"
      },
      {
        "key": "F",
        "symbol": "F",
        "meaning": "thermal forcing driving the westerly current"
      },
      {
        "key": "G",
        "symbol": "G",
        "meaning": "forcing that sustains the weather waves"
      }
    ],
    "code": "o[0] = -x[1]*x[1] - x[2]*x[2] - p.a*x[0] + p.a*p.F;\no[1] = x[0]*x[1] - p.b*x[0]*x[2] - x[1] + p.G;\no[2] = p.b*x[0]*x[1] + x[0]*x[2] - x[2];",
    "links": [
      {
        "label": "Lorenz 84 model (Wikipedia)",
        "url": "https://en.wikipedia.org/wiki/Lorenz_96_model"
      },
      {
        "label": "Lorenz 1984, Irregularity: a fundamental property of the atmosphere",
        "url": "https://onlinelibrary.wiley.com/doi/10.1111/j.1600-0870.1984.tb00230.x"
      }
    ]
  },
  "rabinovich-fabrikant": {
    "title": "Rabinovich–Fabrikant",
    "about": "An attractor from plasma and wave physics, known for its delicate, hard-to-find chaotic regions. A strange attractor is a path that never repeats yet stays on one fractal shape. Its equations model how waves in a nonlinear medium interact and self-modulate.",
    "howItWorks": "Cubic feedback terms in x and y let the waves amplify and saturate each other, producing intricate chaos that is very sensitive to the parameters.",
    "equations": [
      {
        "label": "",
        "latex": "\\begin{aligned}\\dot{x}&=y\\,(z-1+x^{2})+g\\,x\\\\\\dot{y}&=x\\,(3z+1-x^{2})+g\\,y\\\\\\dot{z}&=-2z\\,(a+xy)\\end{aligned}"
      }
    ],
    "params": [
      {
        "key": "a",
        "symbol": "a",
        "meaning": "controls how strongly z is damped by the wave interaction"
      },
      {
        "key": "g",
        "symbol": "\\gamma",
        "meaning": "linear gain on x and y that energizes the waves"
      }
    ],
    "code": "o[0] = x[1]*(x[2]-1+x[0]*x[0]) + p.g*x[0];\no[1] = x[0]*(3*x[2]+1-x[0]*x[0]) + p.g*x[1];\no[2] = -2*x[2]*(p.a + x[0]*x[1]);",
    "links": [
      {
        "label": "Rabinovich–Fabrikant equations (Wikipedia)",
        "url": "https://en.wikipedia.org/wiki/Rabinovich%E2%80%93Fabrikant_equations"
      }
    ]
  },
  "sprott-linz-f": {
    "title": "Sprott-Linz F",
    "about": "One of a famous catalog of the algebraically simplest chaotic flows, found by computer search. A strange attractor is a never-repeating trajectory bound to a single shape. This one needs just a single tunable number yet still produces genuine chaos.",
    "howItWorks": "A simple rotation in x and y plus one squared term in z is just enough nonlinearity to fold the flow into a chaotic loop.",
    "equations": [
      {
        "label": "",
        "latex": "\\begin{aligned}\\dot{x}&=y+z\\\\\\dot{y}&=-x+a\\,y\\\\\\dot{z}&=x^{2}-z\\end{aligned}"
      }
    ],
    "params": [
      {
        "key": "a",
        "symbol": "a",
        "meaning": "the single tuning knob; sets how much the y motion is amplified"
      }
    ],
    "code": "o[0] = x[1] + x[2];\no[1] = -x[0] + p.a * x[1];\no[2] = x[0] * x[0] - x[2];",
    "links": [
      {
        "label": "Sprott, Simplest dissipative chaotic flows",
        "url": "https://sprott.physics.wisc.edu/pubs/paper212.htm"
      },
      {
        "label": "List of chaotic maps / Sprott systems (Wikipedia)",
        "url": "https://en.wikipedia.org/wiki/List_of_chaotic_maps"
      }
    ]
  },
  "wang-four-wing": {
    "title": "Wang Four-Wing",
    "about": "An attractor engineered to fold into four distinct wings at once. A strange attractor is a path that wanders forever without repeating while staying on one shape. Multi-wing systems like this are studied for use in chaos-based secure communication.",
    "howItWorks": "Products of the coordinates create four lobes, and the trajectory jumps chaotically between all of them.",
    "equations": [
      {
        "label": "",
        "latex": "\\begin{aligned}\\dot{x}&=a\\,x+yz\\\\\\dot{y}&=b\\,x+c\\,y-xz\\\\\\dot{z}&=-z+d\\,xy\\end{aligned}"
      }
    ],
    "params": [
      {
        "key": "a",
        "symbol": "a",
        "meaning": "growth rate on x"
      },
      {
        "key": "b",
        "symbol": "b",
        "meaning": "how strongly x feeds into y"
      },
      {
        "key": "c",
        "symbol": "c",
        "meaning": "damping/growth on y"
      },
      {
        "key": "d",
        "symbol": "d",
        "meaning": "strength of the x-y product driving z"
      }
    ],
    "code": "o[0] = p.a*x[0] + x[1]*x[2];\no[1] = p.b*x[0] + p.c*x[1] - x[0]*x[2];\no[2] = -x[2] + p.d*x[0]*x[1];",
    "links": [
      {
        "label": "Wang & Zhang four-wing attractor (chaos literature)",
        "url": "https://www.hindawi.com/journals/mpe/2012/257916/"
      }
    ]
  },
  "bouali": {
    "title": "Bouali",
    "about": "An attractor derived from a model of economic and predator-prey-like dynamics. A strange attractor is a non-repeating trajectory confined to a single fractal shape. Bouali's system shows how feedback and competition can drive a system into sustained chaos.",
    "howItWorks": "Logistic-style saturation terms (the 1 minus a variable factors) cap the growth of x and y, while a slow z variable nudges the whole flow, producing chaotic oscillation.",
    "equations": [
      {
        "label": "",
        "latex": "\\begin{aligned}\\dot{x}&=a\\,x\\,(1-y)-b\\,z\\\\\\dot{y}&=-c\\,y\\,(1-x^{2})\\\\\\dot{z}&=d\\,x\\end{aligned}"
      }
    ],
    "params": [
      {
        "key": "a",
        "symbol": "a",
        "meaning": "growth rate of x, throttled by y"
      },
      {
        "key": "b",
        "symbol": "b",
        "meaning": "how strongly the slow variable z drags on x"
      },
      {
        "key": "c",
        "symbol": "c",
        "meaning": "decay rate of y, modulated by x squared"
      },
      {
        "key": "d",
        "symbol": "d",
        "meaning": "tiny rate at which x slowly builds up z"
      }
    ],
    "code": "o[0] = p.a*x[0]*(1 - x[1]) - p.b*x[2];\no[1] = -p.c*x[1]*(1 - x[0]*x[0]);\no[2] = p.d*x[0];",
    "links": [
      {
        "label": "Bouali attractor (chaotic-attractors reference)",
        "url": "https://www.dynamicmath.xyz/strange-attractors/"
      }
    ]
  },
  "nose-hoover": {
    "title": "Nosé–Hoover",
    "about": "An attractor that comes from thermostatted molecular-dynamics physics rather than a deliberate chaos design. A strange attractor is a path that never repeats while staying on one shape. Unusually, it is conservative-like rather than dissipative, so the cloud of points does not collapse to a thin sheet.",
    "howItWorks": "It models a single oscillator coupled to a feedback 'thermostat' variable z that speeds it up or slows it down to hold an average energy, and that feedback makes the motion chaotic.",
    "equations": [
      {
        "label": "",
        "latex": "\\begin{aligned}\\dot{x}&=y\\\\\\dot{y}&=-x+yz\\\\\\dot{z}&=a-y^{2}\\end{aligned}"
      }
    ],
    "params": [
      {
        "key": "a",
        "symbol": "a",
        "meaning": "the target 'temperature' the thermostat tries to hold (sets the energy level)"
      }
    ],
    "code": "o[0] = x[1];\no[1] = -x[0] + x[1]*x[2];\no[2] = p.a - x[1]*x[1];",
    "links": [
      {
        "label": "Nosé–Hoover thermostat (Wikipedia)",
        "url": "https://en.wikipedia.org/wiki/Nos%C3%A9%E2%80%93Hoover_thermostat"
      },
      {
        "label": "Sprott, Nosé–Hoover oscillator",
        "url": "https://sprott.physics.wisc.edu/chaos/comchaos.htm"
      }
    ]
  },
  "chua": {
    "title": "Chua (cubic)",
    "about": "The attractor from Chua's circuit, the first chaotic system built and demonstrated in real electronic hardware. A strange attractor is a never-repeating trajectory bound to one shape. This 'double-scroll' form proved chaos is a physical, reproducible phenomenon, not just a numerical curiosity.",
    "howItWorks": "This smooth version replaces Chua's piecewise-linear diode with a cubic nonlinearity, and that cubic term is what folds the voltages into two interlocking scrolls.",
    "equations": [
      {
        "label": "",
        "latex": "\\begin{aligned}\\dot{x}&=\\alpha\\,\\big(y-x-(c_{1}x^{3}+c_{0}x)\\big)\\\\\\dot{y}&=x-y+z\\\\\\dot{z}&=-\\beta\\,y\\end{aligned}"
      }
    ],
    "params": [
      {
        "key": "alpha",
        "symbol": "\\alpha",
        "meaning": "capacitor coupling that sets the time scale of the x dynamics"
      },
      {
        "key": "beta",
        "symbol": "\\beta",
        "meaning": "inductor coupling controlling the z feedback"
      },
      {
        "key": "c0",
        "symbol": "c_{0}",
        "meaning": "linear part of the cubic diode characteristic"
      },
      {
        "key": "c1",
        "symbol": "c_{1}",
        "meaning": "cubic part of the diode characteristic (the key nonlinearity)"
      }
    ],
    "code": "o[0] = p.alpha*(x[1] - x[0] - (p.c1*x[0]*x[0]*x[0] + p.c0*x[0]));\no[1] = x[0] - x[1] + x[2];\no[2] = -p.beta * x[1];",
    "links": [
      {
        "label": "Chua's circuit (Wikipedia)",
        "url": "https://en.wikipedia.org/wiki/Chua%27s_circuit"
      },
      {
        "label": "Multiscroll / double-scroll attractor (Wikipedia)",
        "url": "https://en.wikipedia.org/wiki/Multiscroll_attractor"
      }
    ]
  },
  "clifford": {
    "title": "Clifford Attractor",
    "about": "A single point is fed over and over through a pair of sine-and-cosine formulas, and the trail of where it lands traces out a delicate, often butterfly- or web-like shape. Seed 100,000 points near the same spot and they all collapse onto this same shape, called an attractor. Tiny changes to the four dials produce wildly different forms.",
    "howItWorks": "Each step replaces the point's coordinates with sines and cosines of the old coordinates, so the point hops around the plane while staying trapped on the attractor.",
    "equations": [
      {
        "label": "",
        "latex": "\\begin{aligned} x_{n+1} &= \\sin(a\\,y_n) + c\\cos(a\\,x_n) \\\\ y_{n+1} &= \\sin(b\\,x_n) + d\\cos(b\\,y_n) \\end{aligned}"
      }
    ],
    "params": [
      {
        "key": "a",
        "symbol": "a",
        "meaning": "frequency in the first sine/cosine pair (shapes the x-fold)"
      },
      {
        "key": "b",
        "symbol": "b",
        "meaning": "frequency in the second sine/cosine pair (shapes the y-fold)"
      },
      {
        "key": "c",
        "symbol": "c",
        "meaning": "how strongly the cosine term stretches x"
      },
      {
        "key": "d",
        "symbol": "d",
        "meaning": "how strongly the cosine term stretches y"
      }
    ],
    "code": "o[0] = Math.sin(p.a * x[1]) + p.c * Math.cos(p.a * x[0]);\no[1] = Math.sin(p.b * x[0]) + p.d * Math.cos(p.b * x[1]);",
    "links": [
      {
        "label": "Clifford attractor (Paul Bourke)",
        "url": "http://paulbourke.net/fractals/clifford/"
      }
    ]
  },
  "de-jong": {
    "title": "de Jong Attractor",
    "about": "A point is repeatedly run through four sine and cosine terms, and the cloud of visited positions paints intricate, lace-like patterns. All starting points pour onto the same final figure (an attractor), so the famous image appears no matter where you begin. The four dials reshape it dramatically.",
    "howItWorks": "Every step swaps in the difference of a sine and a cosine for each coordinate, mixing the old x and y together to keep the point wandering the attractor.",
    "equations": [
      {
        "label": "",
        "latex": "\\begin{aligned} x_{n+1} &= \\sin(a\\,y_n) - \\cos(b\\,x_n) \\\\ y_{n+1} &= \\sin(c\\,x_n) - \\cos(d\\,y_n) \\end{aligned}"
      }
    ],
    "params": [
      {
        "key": "a",
        "symbol": "a",
        "meaning": "frequency of the sine acting on y in the x update"
      },
      {
        "key": "b",
        "symbol": "b",
        "meaning": "frequency of the cosine acting on x in the x update"
      },
      {
        "key": "c",
        "symbol": "c",
        "meaning": "frequency of the sine acting on x in the y update"
      },
      {
        "key": "d",
        "symbol": "d",
        "meaning": "frequency of the cosine acting on y in the y update"
      }
    ],
    "code": "o[0] = Math.sin(p.a * x[1]) - Math.cos(p.b * x[0]);\no[1] = Math.sin(p.c * x[0]) - Math.cos(p.d * x[1]);",
    "links": [
      {
        "label": "Peter de Jong attractor (Paul Bourke)",
        "url": "http://paulbourke.net/fractals/peterdejong/"
      }
    ]
  },
  "svensson": {
    "title": "Svensson Attractor",
    "about": "A point bounces through a mix of sines and cosines, leaving a trail that fills out a wispy, flame-like attractor. Because all starting points are drawn to the same figure, the pattern emerges reliably from a scattered cloud. Adjusting the dials morphs it into endless variations.",
    "howItWorks": "Each step rebuilds x from sines and y from cosines of the previous coordinates, with two amplitude dials controlling how far the point reaches.",
    "equations": [
      {
        "label": "",
        "latex": "\\begin{aligned} x_{n+1} &= d\\sin(a\\,x_n) - \\sin(b\\,y_n) \\\\ y_{n+1} &= c\\cos(a\\,x_n) + \\cos(b\\,y_n) \\end{aligned}"
      }
    ],
    "params": [
      {
        "key": "a",
        "symbol": "a",
        "meaning": "frequency applied to x in both updates"
      },
      {
        "key": "b",
        "symbol": "b",
        "meaning": "frequency applied to y in both updates"
      },
      {
        "key": "c",
        "symbol": "c",
        "meaning": "amplitude of the cosine term feeding y"
      },
      {
        "key": "d",
        "symbol": "d",
        "meaning": "amplitude of the sine term feeding x"
      }
    ],
    "code": "o[0] = p.d * Math.sin(p.a * x[0]) - Math.sin(p.b * x[1]);\no[1] = p.c * Math.cos(p.a * x[0]) + Math.cos(p.b * x[1]);",
    "links": [
      {
        "label": "Johnny Svensson attractor (Paul Bourke)",
        "url": "http://paulbourke.net/fractals/peterdejong/"
      }
    ]
  },
  "hopalong": {
    "title": "Hopalong Attractor",
    "about": "Named for how the point literally hops across the plane, this map uses a square root and a sign flip to fling the point around, building up large galaxy- or shell-like sweeps. All points settle onto the same broad attractor shape. It comes from Barry Martin and was popularized by A. K. Dewdney.",
    "howItWorks": "Each step sets the new x by subtracting a signed square root of a stretched old x from the old y, then sets the new y to a constant minus the old x.",
    "equations": [
      {
        "label": "",
        "latex": "\\begin{aligned} x_{n+1} &= y_n - \\operatorname{sgn}(x_n)\\sqrt{\\,|b\\,x_n - c|\\,} \\\\ y_{n+1} &= a - x_n \\end{aligned}"
      }
    ],
    "params": [
      {
        "key": "a",
        "symbol": "a",
        "meaning": "constant that the new y is measured down from"
      },
      {
        "key": "b",
        "symbol": "b",
        "meaning": "scales x inside the square root (sets the spread)"
      },
      {
        "key": "c",
        "symbol": "c",
        "meaning": "offset subtracted inside the square root"
      }
    ],
    "code": "o[0] = x[1] - sign(x[0]) * Math.sqrt(Math.abs(p.b * x[0] - p.c));\no[1] = p.a - x[0];",
    "links": [
      {
        "label": "Hopalong attractor (Paul Bourke)",
        "url": "http://paulbourke.net/fractals/hopalong/"
      },
      {
        "label": "A. K. Dewdney, Computer Recreations (Scientific American)",
        "url": "https://en.wikipedia.org/wiki/Barry_Martin_(artist)"
      }
    ]
  },
  "gumowski-mira": {
    "title": "Gumowski-Mira Attractor",
    "about": "Developed at CERN to study the paths of particles in accelerators, this map can produce strikingly organic, almost biological shapes that look like cells, insects, or sea creatures. A point is repeatedly pushed through a nonlinear helper function, and the cloud of visited points forms the attractor. Small tweaks can flip it between calm rings and chaotic swarms.",
    "howItWorks": "Each step uses a special nonlinear function f to bend the coordinates, then feeds the just-updated x straight back into the y update, coupling the two tightly.",
    "equations": [
      {
        "label": "with the nonlinear function f",
        "latex": "f(v) = a\\,v + \\frac{2(1-a)\\,v^2}{1+v^2}"
      },
      {
        "label": "",
        "latex": "\\begin{aligned} x_{n+1} &= b\\,y_n + f(x_n) \\\\ y_{n+1} &= -x_n + f(x_{n+1}) \\end{aligned}"
      }
    ],
    "params": [
      {
        "key": "a",
        "symbol": "a",
        "meaning": "shape of the nonlinear function f (the main character knob)"
      },
      {
        "key": "b",
        "symbol": "b",
        "meaning": "how much the previous y feeds into the new x"
      }
    ],
    "code": "const gm = (a, v) => a * v + (2 * (1 - a) * v * v) / (1 + v * v);\no[0] = p.b * x[1] + gm(p.a, x[0]);\no[1] = -x[0] + gm(p.a, o[0]);",
    "links": [
      {
        "label": "Gumowski-Mira attractor (Paul Bourke)",
        "url": "http://paulbourke.net/fractals/gumowski/"
      }
    ]
  },
  "tinkerbell": {
    "title": "Tinkerbell Map",
    "about": "A point is pushed through quadratic formulas (it squares and multiplies the coordinates), tracing a curved, comma- or wing-shaped attractor that gives the map its whimsical name. Because the basin is limited, points that wander off are reseeded so the figure stays alive. It is a well-studied example of chaos in a simple polynomial map.",
    "howItWorks": "Each step combines squares and products of the old coordinates with linear terms, so the point loops around the curved attractor.",
    "equations": [
      {
        "label": "",
        "latex": "\\begin{aligned} x_{n+1} &= x_n^2 - y_n^2 + a\\,x_n + b\\,y_n \\\\ y_{n+1} &= 2x_n y_n + c\\,x_n + d\\,y_n \\end{aligned}"
      }
    ],
    "params": [
      {
        "key": "a",
        "symbol": "a",
        "meaning": "linear pull on x in the x update"
      },
      {
        "key": "b",
        "symbol": "b",
        "meaning": "linear pull on y in the x update"
      },
      {
        "key": "c",
        "symbol": "c",
        "meaning": "linear pull on x in the y update"
      },
      {
        "key": "d",
        "symbol": "d",
        "meaning": "linear pull on y in the y update"
      }
    ],
    "code": "o[0] = x[0] * x[0] - x[1] * x[1] + p.a * x[0] + p.b * x[1];\no[1] = 2 * x[0] * x[1] + p.c * x[0] + p.d * x[1];",
    "links": [
      {
        "label": "Tinkerbell map (Wikipedia)",
        "url": "https://en.wikipedia.org/wiki/Tinkerbell_map"
      }
    ]
  },
  "ikeda": {
    "title": "Ikeda Map",
    "about": "Born from a model of light bouncing inside a laser cavity, this map rotates and shrinks a point by an angle that depends on how far it sits from the origin. The result is a swirling, hook-shaped attractor. It is a classic textbook example of how a simple physical system can become chaotic.",
    "howItWorks": "Each step computes a distance-dependent rotation angle, then rotates the point by that angle, scales it by u, and shifts x by one.",
    "equations": [
      {
        "label": "rotation angle",
        "latex": "t = 0.4 - \\frac{6}{1 + x_n^2 + y_n^2}"
      },
      {
        "label": "",
        "latex": "\\begin{aligned} x_{n+1} &= 1 + u\\,(x_n\\cos t - y_n\\sin t) \\\\ y_{n+1} &= u\\,(x_n\\sin t + y_n\\cos t) \\end{aligned}"
      }
    ],
    "params": [
      {
        "key": "u",
        "symbol": "u",
        "meaning": "overall shrink/gain factor; near 0.9 the map turns chaotic"
      }
    ],
    "code": "const t = 0.4 - 6.0 / (1 + x[0] * x[0] + x[1] * x[1]);\no[0] = 1 + p.u * (x[0] * Math.cos(t) - x[1] * Math.sin(t));\no[1] = p.u * (x[0] * Math.sin(t) + x[1] * Math.cos(t));",
    "links": [
      {
        "label": "Ikeda map (Wikipedia)",
        "url": "https://en.wikipedia.org/wiki/Ikeda_map"
      }
    ]
  },
  "henon": {
    "title": "Hénon Map",
    "about": "One of the most famous examples of a strange attractor, introduced by astronomer Michel Hénon. A point is folded and stretched each step, and the visited points reveal a thin, banded curve that, zoomed in, repeats its structure forever (a fractal). It is a go-to model for studying deterministic chaos.",
    "howItWorks": "Each step bends x with a quadratic fold and adds the old y, while the new y is just a shrunk copy of the old x, producing the signature stretch-and-fold.",
    "equations": [
      {
        "label": "",
        "latex": "\\begin{aligned} x_{n+1} &= 1 - a\\,x_n^2 + y_n \\\\ y_{n+1} &= b\\,x_n \\end{aligned}"
      }
    ],
    "params": [
      {
        "key": "a",
        "symbol": "a",
        "meaning": "strength of the quadratic fold (sets the chaos)"
      },
      {
        "key": "b",
        "symbol": "b",
        "meaning": "how much the old x is shrunk into the new y"
      }
    ],
    "code": "o[0] = 1 - p.a * x[0] * x[0] + x[1];\no[1] = p.b * x[0];",
    "links": [
      {
        "label": "Hénon map (Wikipedia)",
        "url": "https://en.wikipedia.org/wiki/H%C3%A9non_map"
      }
    ]
  },
  "bedhead": {
    "title": "Bedhead Attractor",
    "about": "A playful map (named by its discoverer) that runs the product and sum of a point's coordinates through sines and cosines, producing tangled, hair-like strands. The cloud of visited points settles onto this messy attractor. The two dials tune how the strands twist and overlap.",
    "howItWorks": "Each step builds the new x from a sine of the coordinate product plus a cosine of their weighted difference, and the new y from x plus a scaled sine of y.",
    "equations": [
      {
        "label": "",
        "latex": "\\begin{aligned} x_{n+1} &= \\sin\\!\\left(\\frac{x_n y_n}{b}\\right) y_n + \\cos(a\\,x_n - y_n) \\\\ y_{n+1} &= x_n + \\frac{\\sin(y_n)}{b} \\end{aligned}"
      }
    ],
    "params": [
      {
        "key": "a",
        "symbol": "a",
        "meaning": "weight on x inside the cosine term"
      },
      {
        "key": "b",
        "symbol": "b",
        "meaning": "divisor that scales the product and the sine of y"
      }
    ],
    "code": "o[0] = Math.sin((x[0] * x[1]) / p.b) * x[1] + Math.cos(p.a * x[0] - x[1]);\no[1] = x[0] + Math.sin(x[1]) / p.b;",
    "links": [
      {
        "label": "Bedhead attractor (Paul Bourke)",
        "url": "http://paulbourke.net/fractals/bedhead/"
      }
    ]
  },
  "pickover": {
    "title": "Pickover 3D Attractor",
    "about": "A three-dimensional cousin of the sine-and-cosine attractors, named after Clifford Pickover. A point drifts through 3D space following coupled trigonometric rules, weaving a ribbon- or shell-like cloud you can view from any angle. All starting points converge to the same 3D attractor.",
    "howItWorks": "Each step updates x, y, and z from sines and cosines of the other coordinates, with z feeding back into x and y so the three axes stay intertwined.",
    "equations": [
      {
        "label": "",
        "latex": "\\begin{aligned} x_{n+1} &= \\sin(a\\,y_n) - z_n\\cos(b\\,x_n) \\\\ y_{n+1} &= z_n\\sin(c\\,x_n) - \\cos(d\\,y_n) \\\\ z_{n+1} &= e\\,\\sin(x_n) \\end{aligned}"
      }
    ],
    "params": [
      {
        "key": "a",
        "symbol": "a",
        "meaning": "frequency of the sine of y feeding x"
      },
      {
        "key": "b",
        "symbol": "b",
        "meaning": "frequency of the cosine of x feeding x"
      },
      {
        "key": "c",
        "symbol": "c",
        "meaning": "frequency of the sine of x feeding y"
      },
      {
        "key": "d",
        "symbol": "d",
        "meaning": "frequency of the cosine of y feeding y"
      },
      {
        "key": "e",
        "symbol": "e",
        "meaning": "amplitude of the z coordinate"
      }
    ],
    "code": "o[0] = Math.sin(p.a * x[1]) - x[2] * Math.cos(p.b * x[0]);\no[1] = x[2] * Math.sin(p.c * x[0]) - Math.cos(p.d * x[1]);\no[2] = p.e * Math.sin(x[0]);",
    "links": [
      {
        "label": "Pickover attractor (Paul Bourke)",
        "url": "http://paulbourke.net/fractals/pickover/"
      },
      {
        "label": "Clifford A. Pickover (Wikipedia)",
        "url": "https://en.wikipedia.org/wiki/Clifford_A._Pickover"
      }
    ]
  },
  "particleLife": {
    "title": "Particle Life",
    "about": "Thousands of colored particles belong to a handful of species, and a random table decides how each species feels about every other one - attraction or repulsion, and crucially not symmetric (red can chase green while green flees red). From this single random table, lifelike structures emerge on their own: cells, membranes, chasers, and drifting blobs. Everything sits in a wrap-around cube and slowly loses energy to friction so the motion settles into living patterns.",
    "howItWorks": "For every nearby pair, a short-range zone always pushes particles apart, while beyond that the species-pair coefficient sets attraction or repulsion that fades to zero at the maximum radius; forces are summed, scaled, and damped by friction each step.",
    "equations": [
      {
        "label": "Force vs. normalized distance (rn = r / r_max)",
        "latex": "F(r_n) = \\begin{cases} \\dfrac{r_n}{\\beta} - 1, & r_n < \\beta \\\\[2ex] A_{ij}\\left(1 - \\dfrac{\\lvert 2r_n - 1 - \\beta \\rvert}{1 - \\beta}\\right), & \\beta \\le r_n < 1 \\\\[1ex] 0, & r_n \\ge 1 \\end{cases}"
      },
      {
        "label": "Velocity update with friction (per neighbor, g = F/r)",
        "latex": "\\mathbf{v} \\leftarrow \\left(\\mathbf{v} + f_s\\, \\Delta t \\sum_{j} \\frac{F(r_n)}{r}\\,\\Delta\\mathbf{x}_j\\right)\\, f_r"
      },
      {
        "label": "Position update (toroidal)",
        "latex": "\\mathbf{x} \\leftarrow \\mathbf{x} + \\mathbf{v}\\,\\Delta t"
      }
    ],
    "params": [
      {
        "key": "radius",
        "symbol": "r_{max}",
        "meaning": "Maximum interaction distance - beyond it particles ignore each other"
      },
      {
        "key": "beta",
        "symbol": "\\beta",
        "meaning": "Width of the inner always-repel zone, as a fraction of r_max"
      },
      {
        "key": "friction",
        "symbol": "f_r",
        "meaning": "Velocity retained each step (lower = more drag, calmer motion)"
      },
      {
        "key": "force",
        "symbol": "f_s",
        "meaning": "Overall strength multiplier on all interactions"
      },
      {
        "key": "species",
        "symbol": "K",
        "meaning": "Number of distinct species (sizes the K×K interaction table)"
      },
      {
        "key": "variant",
        "symbol": "v",
        "meaning": "Seed selecting which random interaction table (ecosystem) is used"
      }
    ],
    "code": "const rn = r / rMax;\nconst F = rn < beta\n  ? rn / beta - 1\n  : A[rowi + sp[j]] * (1 - Math.abs(2 * rn - 1 - beta) * invBeta1);\nconst g = F / r;\nfx += dx * g; fy += dy * g; fz += dz * g;\n// ...\nst[oi + 3] = (st[oi + 3] + fx * fs * dt) * fr;",
    "links": [
      {
        "label": "Particle Life (Tom Mohr / clusters) overview",
        "url": "https://particle-life.com/"
      },
      {
        "label": "Jeffrey Ventrella - Clusters (original)",
        "url": "https://www.ventrella.com/Clusters/"
      },
      {
        "label": "Wikipedia: Artificial life",
        "url": "https://en.wikipedia.org/wiki/Artificial_life"
      }
    ]
  },
  "boids": {
    "title": "Boids (flocking)",
    "about": "A classic model of how flocks, schools, and swarms self-organize without any leader. Each boid follows three simple urges relative to the neighbors it can perceive: don't crowd them, match their direction, and drift toward their center. Tuning the balance of those three urges produces everything from tight schools to loose scattered swarms, all inside a wrap-around cube.",
    "howItWorks": "Each step a boid averages its neighbors' velocities (alignment) and positions (cohesion) and adds a close-range push-away (separation); these blend into a steering acceleration, then speed is clamped between a minimum and maximum.",
    "equations": [
      {
        "label": "Steering acceleration (over N neighbors within r)",
        "latex": "\\mathbf{a} = w_{a}\\!\\left(\\frac{1}{N}\\sum_j \\mathbf{v}_j - \\mathbf{v}_i\\right) + w_{c}\\,\\frac{1}{N}\\sum_j \\Delta\\mathbf{x}_j - w_{s}\\!\\!\\sum_{r_{ij} < r_{sep}} \\frac{\\Delta\\mathbf{x}_j}{r_{ij}^{2}}"
      },
      {
        "label": "Velocity integrate + speed clamp",
        "latex": "\\mathbf{v} \\leftarrow \\mathbf{v} + \\mathbf{a}\\,\\Delta t, \\qquad \\mathbf{v} \\leftarrow \\mathbf{v}\\,\\frac{\\operatorname{clamp}(\\lVert\\mathbf{v}\\rVert,\\ 0.4\\,s_{max},\\ s_{max})}{\\lVert\\mathbf{v}\\rVert}"
      },
      {
        "label": "Position update (toroidal)",
        "latex": "\\mathbf{x} \\leftarrow \\mathbf{x} + \\mathbf{v}\\,\\Delta t"
      }
    ],
    "params": [
      {
        "key": "radius",
        "symbol": "r",
        "meaning": "Perception radius - how far a boid sees neighbors"
      },
      {
        "key": "separation",
        "symbol": "w_s",
        "meaning": "Strength of the close-range push to avoid crowding (acts within 0.45r)"
      },
      {
        "key": "alignment",
        "symbol": "w_a",
        "meaning": "Strength of the urge to match neighbors' direction"
      },
      {
        "key": "cohesion",
        "symbol": "w_c",
        "meaning": "Strength of the urge to move toward neighbors' center"
      },
      {
        "key": "maxSpeed",
        "symbol": "s_{max}",
        "meaning": "Top speed (minimum speed is fixed at 0.4 of this)"
      }
    ],
    "code": "const inv = 1 / count;\nacc[ai] = (avx * inv - st[oi + 3]) * wAli + cox * inv * wCoh + spx * wSep;\n// ... integrate + clamp:\nlet vx = st[o + 3] + acc[ai] * dt;\nconst sp = Math.hypot(vx, vy, vz) || 1e-9;\nconst clamped = sp > maxSpeed ? maxSpeed : sp < minSpeed ? minSpeed : sp;\nconst s = clamped / sp; vx *= s;",
    "links": [
      {
        "label": "Wikipedia: Boids",
        "url": "https://en.wikipedia.org/wiki/Boids"
      },
      {
        "label": "Craig Reynolds - Boids (original site)",
        "url": "https://www.red3d.com/cwr/boids/"
      },
      {
        "label": "Reynolds 1987 SIGGRAPH paper",
        "url": "https://www.red3d.com/cwr/papers/1987/boids.html"
      }
    ]
  },
  "slimeMold": {
    "title": "Slime Mold",
    "about": "A model of Physarum, the brainless slime mold that solves mazes and grows efficient transport networks by leaving and following chemical trails. Many tiny agents crawl across a grid, each dropping a scent and steering toward whichever of three forward 'noses' smells strongest. The trail map constantly blurs and fades, so paths that get reinforced survive while the rest vanish - and lifelike vein networks emerge.",
    "howItWorks": "Each agent samples the trail field at a left, center, and right sensor, turns toward the strongest, steps forward, and deposits scent; the whole field is then blurred with a 3×3 average and multiplied by a decay factor.",
    "equations": [
      {
        "label": "Steering rule (sensors at heading h and h ± sensor angle)",
        "latex": "h \\leftarrow \\begin{cases} h, & C > L \\text{ and } C > R \\\\ h \\pm \\theta_{turn}\\ (\\text{random}), & C < L \\text{ and } C < R \\\\ h + \\theta_{turn}, & L > R \\\\ h - \\theta_{turn}, & R > L \\end{cases}"
      },
      {
        "label": "Move + deposit",
        "latex": "\\mathbf{x} \\leftarrow \\mathbf{x} + s\\,(\\cos h, \\sin h), \\qquad \\Phi(\\mathbf{x}) \\mathrel{+}= 1"
      },
      {
        "label": "Field diffuse (3×3 mean) and decay",
        "latex": "\\Phi'(i,j) = d \\cdot \\frac{1}{9}\\sum_{|p|,|q|\\le 1} \\Phi(i+p,\\ j+q)"
      }
    ],
    "params": [
      {
        "key": "speed",
        "symbol": "s",
        "meaning": "Distance each agent moves forward per step"
      },
      {
        "key": "sensorDist",
        "symbol": "d_s",
        "meaning": "How far ahead the three sensors sample the trail"
      },
      {
        "key": "sensorAngle",
        "symbol": "\\theta_s",
        "meaning": "Angle of the left/right sensors off the heading"
      },
      {
        "key": "turn",
        "symbol": "\\theta_{turn}",
        "meaning": "How sharply an agent turns toward the strongest scent"
      },
      {
        "key": "decay",
        "symbol": "d",
        "meaning": "Fraction of trail kept each step (lower = trails fade faster)"
      },
      {
        "key": "grid",
        "symbol": "W",
        "meaning": "Resolution of the square trail field (W×W cells)"
      }
    ],
    "code": "const fwd = this.sense(x, y, h, sd);\nconst left = this.sense(x, y, h + sa, sd);\nconst right = this.sense(x, y, h - sa, sd);\nif (fwd > left && fwd > right) { /* keep */ }\nelse if (fwd < left && fwd < right) h += (rng() < 0.5 ? 1 : -1) * turn;\nelse if (left > right) h += turn;\nelse if (right > left) h -= turn;\nnx = x + Math.cos(h) * speed; ny = y + Math.sin(h) * speed;\nfield[(ny|0) * W + (nx|0)] += 1; // deposit\n// field: temp[c] = (sum / 9) * decay;",
    "links": [
      {
        "label": "Wikipedia: Physarum polycephalum",
        "url": "https://en.wikipedia.org/wiki/Physarum_polycephalum"
      },
      {
        "label": "Jones 2010 - Characteristics of pattern formation in Physarum",
        "url": "https://uwe-repository.worktribe.com/output/980579"
      },
      {
        "label": "Sage Jenson - Physarum (mxsage)",
        "url": "https://cargocollective.com/sagejenson/physarum"
      }
    ]
  },
  "pointVortices": {
    "title": "Point Vortices",
    "about": "A 2D ideal-fluid sketch built from a handful of tiny spinning points (vortices), each carrying a positive or negative 'circulation' that whirls the fluid around it. The rest of the dots are weightless tracers that simply drift along the combined swirl, so they paint the streamlines. The vortices pair up, orbit, and chase each other while the world wraps around at its edges like a doughnut.",
    "howItWorks": "Each vortex pushes the fluid in a circle around itself, with strength fading with distance; every point sums up the push from all vortices and takes a small step in that direction.",
    "equations": [
      {
        "label": "Induced velocity at point i (sum over vortices)",
        "latex": "\\mathbf{v}_i = \\frac{1}{2\\pi}\\sum_{j}\\frac{\\Gamma_j}{|\\mathbf{r}_{ij}|^2 + \\epsilon^2}\\,(-\\Delta y_{ij},\\ \\Delta x_{ij})"
      },
      {
        "label": "Advection step",
        "latex": "\\mathbf{x}_i \\leftarrow \\mathbf{x}_i + \\mathbf{v}_i\\,\\Delta t"
      }
    ],
    "params": [
      {
        "key": "vortices",
        "symbol": "N_v",
        "meaning": "How many spinning vortex points drive the flow (the rest are passive tracers)"
      },
      {
        "key": "strength",
        "symbol": "\\Gamma",
        "meaning": "Circulation magnitude of each vortex: how hard it whirls the fluid (sign chosen randomly)"
      },
      {
        "key": "softening",
        "symbol": "\\epsilon",
        "meaning": "Smoothing distance that caps the swirl up close so velocities never blow up"
      }
    ],
    "code": "const inv = (gamma[v] * INV2PI) / (dx * dx + dy * dy + soft2);\nvx -= dy * inv; // perpendicular to the separation: (-dy, dx)\nvy += dx * inv;\n// ...\nlet x = st[o] + vel[i*2] * dt;\nlet y = st[o+1] + vel[i*2+1] * dt;",
    "links": [
      {
        "label": "Vortex (Point vortices) - Wikipedia",
        "url": "https://en.wikipedia.org/wiki/Vortex"
      },
      {
        "label": "Biot-Savart law - Wikipedia",
        "url": "https://en.wikipedia.org/wiki/Biot%E2%80%93Savart_law"
      }
    ]
  },
  "quantumFoam": {
    "title": "Quantum-Foam",
    "about": "A reaction-diffusion field where two virtual chemicals, U and V, spread out and react on a wrap-around grid. U is steadily fed in while V is removed; where they mix, V multiplies and eats U, producing spots, stripes, mazes, and dividing-cell patterns. It is the Gray-Scott model, famous for looking uncannily like living tissue or coral growing on its own.",
    "howItWorks": "Every cell averages its neighbors (diffusion) and runs the reaction U + 2V -> 3V, with feed adding U and kill removing V, repeated step after step.",
    "equations": [
      {
        "label": "Gray-Scott reaction-diffusion",
        "latex": "\\begin{aligned}\\partial_t u &= D_u\\,\\nabla^2 u - u v^2 + f\\,(1 - u)\\\\\\partial_t v &= D_v\\,\\nabla^2 v + u v^2 - (f + k)\\,v\\end{aligned}"
      },
      {
        "label": "9-point Laplacian (orthogonal 0.2, diagonal 0.05)",
        "latex": "\\nabla^2 u \\approx 0.2\\!\\sum_{\\text{edge}} u + 0.05\\!\\sum_{\\text{diag}} u - u"
      }
    ],
    "params": [
      {
        "key": "feed",
        "symbol": "f",
        "meaning": "Feed rate: how fast fresh U is replenished everywhere"
      },
      {
        "key": "kill",
        "symbol": "k",
        "meaning": "Kill rate: how fast V is removed (with feed, sets which pattern emerges)"
      },
      {
        "key": "diffU",
        "symbol": "D_u",
        "meaning": "How quickly chemical U spreads to neighboring cells"
      },
      {
        "key": "diffV",
        "symbol": "D_v",
        "meaning": "How quickly chemical V spreads to neighboring cells"
      },
      {
        "key": "relief",
        "symbol": "h",
        "meaning": "Display only: how much the V concentration lifts the grid into 3D relief"
      }
    ],
    "code": "const uvv = uc * vc * vc;\nun[c] = uc + (Du * lapU - uvv + f * (1 - uc));\nvn[c] = vc + (Dv * lapV + uvv - (f + k) * vc);",
    "links": [
      {
        "label": "Reaction-diffusion system - Wikipedia",
        "url": "https://en.wikipedia.org/wiki/Reaction%E2%80%93diffusion_system"
      },
      {
        "label": "Pearson, Complex Patterns in a Simple System (Science 1993)",
        "url": "https://www.science.org/doi/10.1126/science.261.5118.189"
      },
      {
        "label": "Karl Sims - Reaction-Diffusion Tutorial",
        "url": "https://www.karlsims.com/rd.html"
      }
    ]
  },
  "excitableMedium": {
    "title": "Excitable Medium",
    "about": "A grid of cells that each cycle through phases like a heartbeat: resting, then excited, then a recovery period, then back to rest. A resting cell only fires when enough of its neighbors are currently excited, so activity ripples outward. From a random start this self-organizes into traveling waves and rotating spirals, the same look as the Belousov-Zhabotinsky chemical reaction.",
    "howItWorks": "Excited and recovering cells just advance to the next phase each tick; a resting cell becomes excited only if at least 'threshold' of its 8 neighbors are excited.",
    "equations": [
      {
        "label": "Greenberg-Hastings state transition",
        "latex": "s_i' = \\begin{cases} 1 & s_i = 0 \\text{ and } E_i \\geq \\tau \\\\ 0 & s_i = 0 \\text{ and } E_i < \\tau \\\\ s_i + 1 & 0 < s_i < N-1 \\\\ 0 & s_i = N-1 \\end{cases}"
      },
      {
        "label": "Excited-neighbor count (8-neighborhood)",
        "latex": "E_i = \\#\\{\\,j \\in \\mathcal{N}_8(i) : s_j = 1\\,\\}"
      }
    ],
    "params": [
      {
        "key": "states",
        "symbol": "N",
        "meaning": "Number of phases each cell cycles through (longer recovery = wider waves)"
      },
      {
        "key": "threshold",
        "symbol": "\\tau",
        "meaning": "How many excited neighbors are needed to ignite a resting cell"
      },
      {
        "key": "relief",
        "symbol": "h",
        "meaning": "Display only: how much a cell's phase lifts it into 3D relief (excited rides highest)"
      }
    ],
    "code": "if (cur === 0) {\n  let exc = 0; /* count of the 8 neighbours with s === 1 */\n  nx[c] = exc >= thr ? 1 : 0;\n} else {\n  nx[c] = cur >= N - 1 ? 0 : cur + 1;\n}",
    "links": [
      {
        "label": "Greenberg-Hastings cellular automaton",
        "url": "https://en.wikipedia.org/wiki/Cyclic_cellular_automaton"
      },
      {
        "label": "Excitable medium - Wikipedia",
        "url": "https://en.wikipedia.org/wiki/Excitable_medium"
      },
      {
        "label": "Belousov-Zhabotinsky reaction - Wikipedia",
        "url": "https://en.wikipedia.org/wiki/Belousov%E2%80%93Zhabotinsky_reaction"
      }
    ]
  },
  "hyperOscillator": {
    "title": "Hyper-Oscillator",
    "about": "Each particle is a tiny stack of spinning hands, like nested clock hands of a clock-within-a-clock. Every level turns at its own speed set by a famous never-repeating number (the golden ratio, pi, e, ...), and each level is nudged by the one above it, so the swirling pattern drifts forever without exactly repeating. The result is a shimmering, quasi-periodic swarm that stays bounded no matter the step size.",
    "howItWorks": "Each level's spin rate is its base frequency multiplied by a wobble that depends on its parent level's current angle (the coupling), and the final 3D position is built by summing the nested hands with shrinking lengths.",
    "equations": [
      {
        "label": "Per-level phase update (parent-coupled)",
        "latex": "\\dot{\\theta}_k = \\omega_k\\,\\bigl(1 + \\varepsilon \\sin\\theta_{k-1}\\bigr)"
      },
      {
        "label": "Per-level angular frequency from irrational drivers",
        "latex": "\\omega_k = \\omega_0\\, S_f^{\\,k}\\, d_{k}"
      },
      {
        "label": "Nested epicycle position (amplitude A_k = S_a^k)",
        "latex": "\\begin{aligned} x &= \\sum_{k=0}^{L-1} S_a^{\\,k} \\cos\\theta_k \\\\ y &= \\sum_{k=0}^{L-1} S_a^{\\,k} \\sin\\theta_k \\\\ z &= \\sum_{k=0}^{L-1} S_a^{\\,k} \\sin(\\theta_k - \\theta_{k-1}) \\end{aligned}"
      }
    ],
    "params": [
      {
        "key": "omega0",
        "symbol": "\\omega_0",
        "meaning": "Base spin speed of the slowest (innermost) level; everything else scales off it"
      },
      {
        "key": "freqScale",
        "symbol": "S_f",
        "meaning": "How much faster each deeper level spins than the one above it"
      },
      {
        "key": "ampScale",
        "symbol": "S_a",
        "meaning": "How much shorter each deeper level's hand is (must be under 1, so the sum stays bounded)"
      },
      {
        "key": "eps",
        "symbol": "\\varepsilon",
        "meaning": "Coupling strength: how strongly a parent level's angle wobbles its child's spin rate"
      },
      {
        "key": "levels",
        "symbol": "L",
        "meaning": "Number of nested levels (3-6); a structural choice that rebuilds the system"
      }
    ],
    "code": "// per-level phase derivative (parent-coupled)\nlet parent = 0;\nfor (let k = 0; k < L; k++) {\n  out[k] = om[k] * (1 + eps * Math.sin(parent));\n  parent = x[k];\n}\n\n// per-level angular frequency (precomputed each step)\nfor (let k = 0; k < L; k++)\n  this.omega[k] = w0 * Math.pow(sf, k) * IRRATIONAL_DRIVERS[k % IRRATIONAL_DRIVERS.length];\n\n// nested epicycle position\nlet amp = 1, prev = 0;\nfor (let k = 0; k < L; k++) {\n  const th = st[so + k];\n  x += amp * Math.cos(th);\n  y += amp * Math.sin(th);\n  z += amp * Math.sin(th - prev);\n  prev = th; amp *= aScale;\n}",
    "links": [
      {
        "label": "Deferent and epicycle (nested circular motion)",
        "url": "https://en.wikipedia.org/wiki/Deferent_and_epicycle"
      },
      {
        "label": "Quasiperiodic motion",
        "url": "https://en.wikipedia.org/wiki/Quasiperiodicity"
      },
      {
        "label": "Coupled oscillators / phase coupling (Kuramoto model)",
        "url": "https://en.wikipedia.org/wiki/Kuramoto_model"
      }
    ]
  },
  "nbody": {
    "title": "N-Body",
    "about": "A swarm of equal-mass points that all pull on each other by gravity, seeded as a few orbiting clusters that merge, sling-shot, and form tails over time. To avoid infinite forces when two points get very close, the gravity is softened with a small cushion distance. It uses a stable, energy-preserving integration scheme so the orbits stay realistic over long runs.",
    "howItWorks": "Every step it adds up the softened gravitational pull from all other particles on each one, then advances positions and velocities with velocity-Verlet (move, recompute the pull, then nudge the velocity by the average of the old and new accelerations).",
    "equations": [
      {
        "label": "Plummer-softened acceleration (sum over all other bodies)",
        "latex": "\\mathbf{a}_i = G\\sum_{j \\neq i} \\frac{\\mathbf{r}_j - \\mathbf{r}_i}{\\bigl(\\lVert \\mathbf{r}_j - \\mathbf{r}_i \\rVert^2 + \\varepsilon^2\\bigr)^{3/2}}"
      },
      {
        "label": "Optional cross-scale pull toward the centre of mass",
        "latex": "\\mathbf{a}_i \\mathrel{+}= c\\,(\\bar{\\mathbf{r}} - \\mathbf{r}_i), \\qquad \\bar{\\mathbf{r}} = \\frac{1}{n}\\sum_{k} \\mathbf{r}_k"
      },
      {
        "label": "Velocity-Verlet integration",
        "latex": "\\begin{aligned} \\mathbf{r}_i &\\leftarrow \\mathbf{r}_i + \\mathbf{v}_i\\,\\Delta t + \\tfrac{1}{2}\\mathbf{a}_i\\,\\Delta t^2 \\\\ \\mathbf{v}_i &\\leftarrow \\mathbf{v}_i + \\tfrac{1}{2}\\bigl(\\mathbf{a}_i^{\\text{old}} + \\mathbf{a}_i^{\\text{new}}\\bigr)\\Delta t \\end{aligned}"
      }
    ],
    "params": [
      {
        "key": "G",
        "symbol": "G",
        "meaning": "Gravitational strength; how hard every particle pulls on the others"
      },
      {
        "key": "softening",
        "symbol": "\\varepsilon",
        "meaning": "Cushion distance that caps the force at close range, preventing infinite blow-ups"
      },
      {
        "key": "spin",
        "symbol": "s",
        "meaning": "Initial rotational speed given to each cluster (both internal swirl and bulk orbit)"
      },
      {
        "key": "coupling",
        "symbol": "c",
        "meaning": "Strength of a gentle extra pull toward the whole swarm's centre of mass, keeping it on-screen"
      },
      {
        "key": "clusters",
        "symbol": "K",
        "meaning": "Number of starting clusters (1-6); a structural choice that rebuilds the system"
      }
    ],
    "code": "// Plummer-softened pairwise acceleration\nconst dx = st[oj] - xi, dy = st[oj+1] - yi, dz = st[oj+2] - zi;\nconst r2 = dx*dx + dy*dy + dz*dz + eps2;\nconst inv = 1 / (r2 * Math.sqrt(r2)); // (r^2+eps^2)^(-3/2)\nconst f = G * m * inv;\naxi += dx*f; ayi += dy*f; azi += dz*f;\na[aj] -= dx*f; a[aj+1] -= dy*f; a[aj+2] -= dz*f; // Newton's 3rd law\n\n// velocity-Verlet step\nst[o]   += st[o+3]*dt + a[ai]*halfDt2;   // drift\nst[o+3] += a[ai]*0.5*dt;                  // half-kick (old accel)\n// ... recompute accel ...\nst[o+3] += a[ai]*0.5*dt;                  // half-kick (new accel)",
    "links": [
      {
        "label": "N-body simulation",
        "url": "https://en.wikipedia.org/wiki/N-body_simulation"
      },
      {
        "label": "Plummer model (softened gravity)",
        "url": "https://en.wikipedia.org/wiki/Plummer_model"
      },
      {
        "label": "Verlet integration (velocity-Verlet)",
        "url": "https://en.wikipedia.org/wiki/Verlet_integration"
      }
    ]
  }
};
